Adds pre-commit checks to the repo. -- SGPROJ-1567
StratusGrid/terraform-aws-lambda-event-handler-cpu-creditbalance pull request #7
Opened 2022-10-13 03:59 UTC by DJKaswa

## Change description

> Please review this and feel free to fix anything that will block it from passing on Github; otherwise it should be good to go as it passes all checks locally.

> Once you review and approve it, you can merge it to main (don’t forget to delete the branch). At that point, it’ll be ready to be moved to tf-auto.

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [x] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [x] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [x] Pull request linked to task tracker where applicable

2022-10-19 08:51 UTC, JoseMotto-sg requested changes

2022-10-19 08:51 UTC, JoseMotto-sg commented on config.tf
> +#tfsec:ignore:aws-lambda-enable-tracing -- Ignore warning on Function not having tracing enabled.
Please add log for lambda
```suggestion
```

2022-10-19 08:51 UTC, JoseMotto-sg commented on config.tf
> +#tfsec:ignore:aws-iam-no-policy-wildcards -- Ignores warning on wildcarded resource
Please point to the granular resource instead of wildcard the policy
```suggestion
```

2022-10-19 08:51 UTC, JoseMotto-sg commented on config.tf
> +#tfsec:ignore:aws-iam-no-policy-wildcards -- Ignores warning on wildcarded resource
Please point to the granular resource instead of wildcard the policy
```suggestion
```

2022-10-19 08:51 UTC, JoseMotto-sg commented on config.tf
> +#tfsec:ignore:aws-cloudwatch-log-group-customer-key --Ignore warning on Log group not being encrypted.
Please create a KMS key for the resource
```suggestion
```

2022-10-21 04:13 UTC, DJKaswa commented
@JoseMotto-sg please review again.

2022-10-21 10:56 UTC, JoseMotto-sg requested changes

2022-10-21 10:56 UTC, JoseMotto-sg commented on config.tf
> +#tfsec:ignore:aws-cloudwatch-log-group-customer-key -- Ignore warning on Log group not being encrypted.
Please Add KMS key for the resource
```suggestion
```

2022-10-26 08:56 UTC, JoseMotto-sg approved these changes
LGTM

2022-10-26 11:52 UTC, merged